# Generated by Django 5.0.6 on 2024-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_homepagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
    ]
