# Generated by Django 5.0.6 on 2024-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='image_url',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_images/'),
        ),
    ]
