# Generated by Django 5.0.6 on 2024-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_feature_description_remove_feature_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConnected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='restaurant_icons/')),
            ],
        ),
    ]
