# Generated by Django 5.0.6 on 2024-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='restaurantconnected',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_icons/'),
        ),
    ]
