# Generated by Django 5.0.6 on 2024-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraphs', models.TextField()),
                ('roots_title', models.CharField(blank=True, default='', max_length=255)),
                ('roots_content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
