# Generated by Django 5.0.6 on 2024-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_aboutussection1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsIndustriesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('industries_list', models.TextField()),
            ],
        ),
    ]
