# Generated by Django 5.0.6 on 2024-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_aboutusindustriessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraphs', models.TextField()),
            ],
        ),
    ]
