# Generated by Django 5.0.6 on 2024-07-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_contactussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pricing_images/')),
            ],
        ),
    ]
